# Generated by Django 3.2.5 on 2021-07-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='null', max_length=10)),
                ('title', models.CharField(default='', max_length=100)),
                ('content', models.CharField(default='', max_length=1000000)),
                ('author', models.CharField(default='', max_length=100)),
                ('pubished', models.DateTimeField(default='', max_length=100)),
                ('uses', models.IntegerField(default=0)),
            ],
        ),
    ]
