# Generated by Django 3.2.5 on 2021-07-27 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='pubished',
            new_name='published',
        ),
    ]
