# Generated by Django 3.2.5 on 2021-07-30 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_pubished_resource_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=100),
        ),
    ]
