# Generated by Django 3.2.5 on 2021-08-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_resource_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='style',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
