# Generated by Django 3.2.5 on 2021-08-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210811_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='link',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
