# Generated by Django 3.2.5 on 2021-08-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_resource_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
