# Generated by Django 3.2.5 on 2021-07-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210712_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='room',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
