# Generated by Django 3.2.5 on 2021-07-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
