# Generated by Django 3.2.5 on 2021-07-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210714_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ideology',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
