# Generated by Django 3.2.5 on 2021-07-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_ideology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='style',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='topic',
        ),
        migrations.AlterField(
            model_name='profile',
            name='ideology',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
