# Generated by Django 3.2.5 on 2021-07-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210715_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ideology',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
