# Generated by Django 3.2.5 on 2021-07-18 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter', models.CharField(max_length=25)),
                ('offender', models.CharField(max_length=25)),
                ('date', models.CharField(default=datetime.datetime.now, max_length=100)),
                ('profanity', models.BooleanField(default=False)),
                ('discrimination', models.BooleanField(default=False)),
                ('inappropriate', models.BooleanField(default=False)),
                ('sexual', models.BooleanField(default=False)),
                ('bot', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
    ]
