# Generated by Django 3.2.5 on 2021-07-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='bot',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='discrimination',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='inappropriate',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='message',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='report',
            name='profanity',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='sexual',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
