# Generated by Django 3.2.5 on 2021-07-24 22:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rater', models.CharField(max_length=25)),
                ('recipient', models.CharField(max_length=25)),
                ('rating', models.IntegerField(default=100)),
                ('message', models.CharField(max_length=1000)),
                ('date', models.CharField(default=datetime.datetime.now, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('auo', models.CharField(max_length=25, null=True)),
                ('aut', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000)),
                ('date', models.CharField(default=datetime.datetime.now, max_length=100)),
                ('room', models.CharField(default='default', max_length=1000)),
                ('sender', models.CharField(default='anon', max_length=35)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
