# Generated by Django 3.2.5 on 2021-07-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='topic',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
