# Generated by Django 3.2.5 on 2021-08-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_room_group_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='aut',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
